import { ref } from 'vue';

export class LabResultClass {
        constructor() {
            this["Fecha"] = null;
            this.Creatinina = null;
            this.Lactato = null;
            this["Sodio (Na)"] = null;
            this["Potasio (K)"] = null;
            this["Cloro (Cl)"] = null;
            this.proBNP = null;
            this.Calcio = null;
            this.Uremia = null;
            this["Nitrogeno ureico"] = null;
            this.Magnesio = null;
            this.Fosforo = null;
            this["Bilirrubina Total"] = null;
            this["Bilirrubina Directa"] = null;
            this["ASAT/GOT"] = null;
            this["ALAT/GPT"] = null;
            this["Gama GT"] = null;
            this["Fosfatasas Alcalinas"] = null;
            this["Troponina I"] = null;
            this.LDH = null;
            this.Albumina = null;
            this.Proteinas = null;
            this.PCR = null;
            this.Glucosa = null;
            this.Trigliceridos = null;
            this["CK Total"] = null;
            this["CK MB"] = null;
            this["V.H.S."] = null;
            this.Hematocrito = null;
            this.Hemoglobina = null;
            this["Recuento Hematíes"] = null;
            this.VCM = null;
            this.HCM = null;
            this.CHCM = null;
            this["Recuento Leucocitos"] = null;
            this["Recuento de Plaquetas"] = null;
            this.RDW = null;
            this["Segmentados %"] = null;
            this["Linfocitos %"] = null;
            this["Monocitos %"] = null;
            this["Basófilos %"] = null;
            this["Eosinófilos %"] = null;
            this["Eosinófilos"] = null;
            this["Basófilos"] = null;
            this["Segmentados"] = null;
            this["Linfocitos"] = null;
            this["Monocitos"] = null;
            this.pH = null;
            this.pO2 = null;
            this.pCO2 = null;
            this.tCO2 = null;
            this["HCO3-"] = null;
            this["BE (B)"] = null;
            this.sO2 = null;
            this.INR = null;
            this["Tiempo de protrombina %"] = null;
            this["Tiempo de protrombina seg"] = null;
            this.TTPK = null;
        }
    }